"use client";

import { LandingNav } from "@/components/layout/LandingNav";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-50 flex flex-col">
      <LandingNav />
      <main className="mx-auto max-w-3xl px-4 py-16 flex-grow">
        <h1 className="text-3xl font-bold tracking-tight text-zinc-900 mb-8">Terms of Service</h1>
        <div className="prose prose-zinc prose-sm">
          <p>Last updated: March 28, 2026</p>
          <h2 className="text-lg font-bold mt-6 mb-2">1. Acceptance of Terms</h2>
          <p>By using PG Trust, you agree to these terms. If you do not agree, please do not use our services.</p>
          
          <h2 className="text-lg font-bold mt-6 mb-2">2. Accuracy of Information</h2>
          <p>Users are responsible for ensuring all provided information, including ID verification and property details, is accurate and up-to-date.</p>

          <h2 className="text-lg font-bold mt-6 mb-2">3. Trust Scores</h2>
          <p>The Trust Score is a proprietary metric generated by PG Trust based on user behavior and feedback. It is intended for informational purposes within the platform ecosystem.</p>

          <h2 className="text-lg font-bold mt-6 mb-2">4. User Conduct</h2>
          <p>Users must treat each other with respect. Harassment, fraud, or misuse of the platform will result in immediate termination of access.</p>

          <h2 className="text-lg font-bold mt-6 mb-2">5. Liability</h2>
          <p>PG Trust is a platform connecting tenants and owners. We are not a party to rental agreements and are not liable for any disputes or damages arising from stays.</p>
        </div>
      </main>
    </div>
  );
}
